apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: true
spec:
  containers:
  - name: builder
    image: TODO
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: 8Gi
        cpu: "4"
      requests:
        memory: 4Gi
        cpu: "2"
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run
  - name: docker-daemon
    image: TODO
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  - name: python3
    image: TODO
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: 8Gi
        cpu: "4"
      requests:
        memory: 2Gi
        cpu: "1"
    volumeMounts:
      - name: docker-socket
        mountPath: /var/run
  volumes:
  - name: docker-socket
    emptyDir: {}
  tolerations:
  - key: "jenkins-worker"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    jenkins-worker: "true"
