openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /example
paths:
  /healthy:
    get:
      summary: Health Check
      operationId: health_check_healthy_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}